public enum Especializacao {
    OFTAMOLOGIA, 
    PEDIATRIA,
    DERMATOLOGIA,
    CARDIOLOGIA,
    PSIQUIATRIA, 
    NEUROLOGIA,
    ORTOPEDIA,
    GASTROENTOLOGIA,
    GINECOLOGIA,
    ONCOLOGIA, 
    UROLOGIA, 
    ENDOCRINOLGIA,
    HEMATOLOGIA;
}
